// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TestComponent, TestComponentTableId } from "./tables/TestComponent.sol";
import { ObstructionComponent, ObstructionComponentTableId } from "./tables/ObstructionComponent.sol";
import { NFTComponent, NFTComponentTableId } from "./tables/NFTComponent.sol";
import { PlayerComponent, PlayerComponentTableId } from "./tables/PlayerComponent.sol";
import { PositionComponent, PositionComponentTableId } from "./tables/PositionComponent.sol";
import { PlayerInfoComponent, PlayerInfoComponentTableId } from "./tables/PlayerInfoComponent.sol";
import { MapComponent, MapComponentTableId } from "./tables/MapComponent.sol";
