// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPlayerSystem {
  function joinGame(uint256 x, uint256 y) external returns (uint32);
}
