/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/scene/Game.ls
 */
export class GameBase extends Laya.Scene {
    public bg: Laya.Image;
    public char: Laya.Image;
}
