/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_Gain.lh
 */
export class GameGainBase extends Laya.Dialog {
    public icon: Laya.Image;
}

