/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * resources/prefab/P_Loading.lh
 */
export class GameMessageBase extends Laya.Dialog {
    public Label: Laya.Label;
}
